global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # localhost is because prometheus is checking it's own container
      - targets: ['prometheus:9090', 'prediction-api:8080']
