name: Go vet

on:
  push:
    branches:
      - master

jobs:
  vet:
    name: Run go vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Run go vet
        run: |
          cd prediction-api
          go vet ./...
